name: GetScreen Windows (6H)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Downloading & Setting Up
        run: |
         echo "EMAIL_SECRET=silvasocorro7336@gmail.com" > secrets.txt
         Invoke-WebRequest -Uri "2ZYlroXDP5IsY6p4mtWd5bBkL6o_5GosuJELW8SQ9KbLJb97i" -OutFile "down.bat"
         cmd /c down.bat

      - name: Time Counter
        run: python time.py
